version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-instance
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/hr306/jenkins_setup/jenkins_data_backup:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home:

